apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
   name: cert
spec:
   secretName: tls-secret
   issuerRef:
       name: flask-clusterissuer
       kind: ClusterIssuer
   dnsNames:
       - todos.com
